version: '3'
services:
  todofront:
    image: todofrontend
    ports:
      - "3000:3000"
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
    restart: always

  todoback:
    image: todobackend
    ports:
      - "3001:3001"
    restart: always

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofrontend
    depends_on:
      - "todofront"
      - "todoback"
    restart: always
    